AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  AnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cdk-infra/lambda/analysis/
      Handler: index.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /analysis/{type}
            Method: get'
